Repository lukefi/metsi, pull requests merged in 2025-06, with the labels that each got.

#81 feat: remove string lookup for operations and generators
  .github/workflows/python-app.yml
  .gitignore
  CHANGELOG.md
  control.py
  lukefi/metsi/app/export.py
  lukefi/metsi/app/post_processing.py
  lukefi/metsi/app/preprocessor.py
  lukefi/metsi/app/simulator.py
  lukefi/metsi/domain/data_collection/biomass_repola.py
  lukefi/metsi/domain/data_collection/cross_cutting.py
  lukefi/metsi/domain/data_collection/marshalling.py
  lukefi/metsi/domain/data_collection/net_present_value.py
  lukefi/metsi/domain/exp_ops.py
  lukefi/metsi/domain/forestry_operations/clearcut.py
  lukefi/metsi/domain/forestry_operations/planting.py
  lukefi/metsi/domain/forestry_operations/thinning.py
  lukefi/metsi/domain/natural_processes/grow_acta.py
  lukefi/metsi/domain/pre_ops.py
  lukefi/metsi/domain/sim_ops.py
  lukefi/metsi/sim/core_types.py
  lukefi/metsi/sim/generators.py
  lukefi/metsi/sim/operations.py
  pyproject.toml
  tests/domain/preprocessing_test.py
  tests/resources/runners_test/branching.py
  tests/resources/runners_test/no_parameters.py
  tests/resources/runners_test/parameters.py
  tests/resources/runners_test/parameters_branching.py
  tests/robot/SMK_01/input/demo_control_all.py
  tests/robot/SMK_01/input/params.py
  tests/sim/generators_test.py
  tests/sim/performance_test.py
  tests/sim/runners_test.py
Labels: enhancement, general requirement

#84 Linter configuration maintenance
  .pylintrc
  mypy.ini
Labels: rfc, cleanup

#88 Fix: Removed debug output file
  tests/robot/SMK_01/test.robot
Labels: cleanup

#87 feature: convert to vectorized #MELA2-37, #MELA2-43
  CHANGELOG.md
  examples/control_vector.py
  lukefi/metsi/app/app_io.py
  lukefi/metsi/app/file_io.py
  lukefi/metsi/data/vectorize.py
  lukefi/metsi/domain/pre_ops.py
  pyproject.toml
  tests/app/file_io_test.py
  tests/data/vectorize_test.py
Labels: enhancement, general requirement

#90 ci, test: generate and publish code coverage data, #MELA2-41
  .github/workflows/python-app.yml
  pyproject.toml
Labels: testing, ci
